### ISSUE TITLE
getAccountInfo occasionally returns error

### ISSUE THREAD

**Issue by armaniferrante** [zubr-exchange/cacherpc#48]
It's been reported that `getAccountInfo` occasionally returns 

```
Error: failed to get info about account 2CSEjyDtAtgCjTKyXHZyfUVe7EERtL7rjYjJSgcBPYLf: Invalid params: invalid type: map, expected string at line 1 column 34
```

Gist to reproduce here https://gist.github.com/barry-the-sender/d877a87f23d8d52d32fdd71c01f71481.

**Comment by polachok** [comment]
The request send by the gist looks like this:

```
{"method":"getAccountInfo","jsonrpc":"2.0",
"params":["HTr2pYDBQZP13YTzLdsPzmh6e4hsNeqoGy3B777ejqTT",
{"encoding":"base64",
"commitment":{"commitment":"confirmed"}}],
"id":"d8037b81-954c-43f8-811d-4a93b49cc3f8"}
```
Note that commitment is an object here.

It's documented as a string in RPC API docs:
https://docs.solana.com/developing/clients/jsonrpc-api#configuring-state-commitment

Also documented as a string in JS docs:
https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getAccountInfo
https://solana-labs.github.io/solana-web3.js/modules.html#Commitment

So I would say this is a bug in the client code. What do you think?

**Comment by brianlong** [comment]
I see similar problems from the Solana CLI on Serum RPC & our own RPC.

```
% solana stakes --url https://solana-api.projectserum.com BWjYF7ZX8b7Hbj1VHKJVPvdGmxdh59psWotJb7pLBAUZ

Error: RPC request error: Failed to deserialize RPC error response: {"code":-32602,"message":"Invalid params: invalid type: null, expected a boolean at line 1 column 254"} [missing field `data`]
```

This command currently works as expected on https://api.mainnet-beta.solana.com which is not using the Zubr RPC cache.

**Comment by linuskendall** [comment]
The issue reported by @brianlong is likely caused by withContext being set to 'null'.

This is the request that zubr-cache chokes on:


```
{"id":1,"jsonrpc":"2.0","method":"getProgramAccounts","params":["Stake11111111111111111111111111111111111111",{"commitment":"confirmed","dataSlice":null,"encoding":"base64","filters":[{"memcmp":{"bytes":"3xyZh","encoding":"binary","offset":0}},{"memcmp":{"bytes":"BWjYF7ZX8b7Hbj1VHKJVPvdGmxdh59psWotJb7pLBAUZ","encoding":"binary","offset":124}}],"withContext":null}]}
```

**Comment by linuskendall** [comment]
Re the empty data field. I was testing and I noticed that occasionally it seemed like the cache had stored and/or was returning an empty response. This seems different issue from the withContext: null where the cache actually returns an error.

**Comment by linuskendall** [comment]
Fetching`Stake11111111111111111111111111111111111111` (without any filters) is really snappy without the cache (api.mainnet-beta.solana.com) but seems to hang with the cache both with our servers and project-serum. I am not sure if it's the same issue as discussed above. 

I am not sure if this could be that the zubr-cache is waiting for the entire response to be delivered before it forwards it to the client, and in the middle of the response times out whereas the solana-validator directly writes the response continuously?
